package com.cozygrams.tv;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.InputDevice;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import java.util.HashMap;
import java.util.Map;

public final class CozyGameView extends View {
    private static final int HOME=0,GAME=1,SETTINGS=2;
    private static final int BG=Color.rgb(43,37,62),CREAM=Color.rgb(255,243,220),PINK=Color.rgb(255,120,154),BLUE=Color.rgb(103,197,220),GRID=Color.rgb(104,91,126);
    private final Paint p=new Paint(3);private final RectF rect=new RectF();private final GameState game;private final CozyMusic music=new CozyMusic();private final CozySfx sfx=new CozySfx();private final Bitmap background,garden;
    private final Map<Integer,Integer> players=new HashMap<>();private final Map<Integer,Long> lastMove=new HashMap<>();
    private int screen=HOME,menu;private boolean won,musicOn,sfxOn,gentleCheck,hintsOn;private String toast="Press a button on each controller to join";private long toastAt;
    private final String[] messages={"You make a lovely team!","Piece by piece, you can do anything.","Home is wherever we're together.","Two hearts, one cozy puzzle.","Small steps make beautiful pictures.","The best view is the one we share."};

    public CozyGameView(Context c){super(c);setFocusable(true);setFocusableInTouchMode(true);requestFocus();background=BitmapFactory.decodeResource(getResources(),R.drawable.cozy_room);garden=BitmapFactory.decodeResource(getResources(),R.drawable.moon_garden);SharedPreferences s=c.getSharedPreferences("save",0);long seed=s.getLong("seed",System.currentTimeMillis());int size=s.getInt("size",5);musicOn=s.getBoolean("music",true);sfxOn=s.getBoolean("sfx",true);gentleCheck=s.getBoolean("gentle",false);hintsOn=s.getBoolean("hints",true);game=new GameState(seed,size);game.solved=s.getInt("solved",0);game.storyIndex=s.getInt("storyIndex",0);game.storyMode=s.getBoolean("storyMode",false);if(game.storyMode)game.startStory(game.storyIndex);game.moves[0]=s.getInt("moves0",0);game.moves[1]=s.getInt("moves1",0);sfx.setEnabled(sfxOn);String marks=s.getString("marks","");if(marks.length()==game.size*game.size)for(int i=0;i<marks.length();i++)game.puzzle.marks[i/game.size][i%game.size]=(byte)(marks.charAt(i)-'0');}
    public void resume(){music.setEnabled(musicOn);sfx.setEnabled(sfxOn);}
    public void pause(){music.stop();save();}
    private void save(){StringBuilder b=new StringBuilder(game.size*game.size);for(byte[] row:game.puzzle.marks)for(byte mark:row)b.append((char)('0'+mark));getContext().getSharedPreferences("save",0).edit().putLong("seed",game.seed).putInt("size",game.size).putInt("solved",game.solved).putInt("moves0",game.moves[0]).putInt("moves1",game.moves[1]).putBoolean("music",musicOn).putBoolean("sfx",sfxOn).putBoolean("gentle",gentleCheck).putBoolean("hints",hintsOn).putBoolean("storyMode",game.storyMode).putInt("storyIndex",game.storyIndex).putString("marks",b.toString()).apply();}
    private int player(KeyEvent e){int id=e.getDeviceId();if(!players.containsKey(id)){players.put(id,players.size()%2);toast="Player "+(players.get(id)+1)+" joined  ♥";toastAt=System.currentTimeMillis();}return players.get(id);}
    private boolean confirm(int key){return key==KeyEvent.KEYCODE_BUTTON_A||key==KeyEvent.KEYCODE_DPAD_CENTER||key==KeyEvent.KEYCODE_ENTER;}

    @Override public boolean onKeyDown(int key,KeyEvent e){if(e.getRepeatCount()>0)return true;int who=player(e);
        if(screen==HOME&&key==KeyEvent.KEYCODE_BACK){save();return super.onKeyDown(key,e);}
        if(screen==HOME){if(key==KeyEvent.KEYCODE_DPAD_UP){menu=Math.floorMod(menu-1,5);sfx.play(CozySfx.Sound.MOVE);}else if(key==KeyEvent.KEYCODE_DPAD_DOWN){menu=(menu+1)%5;sfx.play(CozySfx.Sound.MOVE);}else if(menu==2&&(key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_DPAD_RIGHT||confirm(key))){int size=game.storyMode?5:game.size;size+=key==KeyEvent.KEYCODE_DPAD_LEFT?-5:5;if(size>20)size=5;if(size<5)size=20;game.startEndless(System.currentTimeMillis(),size);sfx.play(CozySfx.Sound.SELECT);save();}else if(confirm(key)){sfx.play(CozySfx.Sound.SELECT);if(menu==0)screen=GAME;else if(menu==1){game.startStory(game.storyIndex);screen=GAME;save();}else if(menu==3){screen=SETTINGS;menu=0;}else if(menu==4){game.solved=0;game.startStory(0);save();screen=GAME;}}invalidate();return true;}
        if(screen==SETTINGS){if(key==KeyEvent.KEYCODE_DPAD_UP||key==KeyEvent.KEYCODE_DPAD_DOWN){menu=Math.floorMod(menu+(key==KeyEvent.KEYCODE_DPAD_DOWN?1:-1),5);sfx.play(CozySfx.Sound.MOVE);}else if(confirm(key)){if(menu==0){musicOn=!musicOn;music.setEnabled(musicOn);}else if(menu==1){sfxOn=!sfxOn;sfx.setEnabled(sfxOn);if(sfxOn)sfx.play(CozySfx.Sound.SELECT);}else if(menu==2){gentleCheck=!gentleCheck;sfx.play(CozySfx.Sound.SELECT);}else if(menu==3){hintsOn=!hintsOn;sfx.play(CozySfx.Sound.SELECT);}else{screen=HOME;menu=0;}save();}else if(key==KeyEvent.KEYCODE_BACK||key==KeyEvent.KEYCODE_BUTTON_B){screen=HOME;menu=0;}invalidate();return true;}
        if(key==KeyEvent.KEYCODE_BUTTON_START){screen=SETTINGS;menu=0;invalidate();return true;}if(key==KeyEvent.KEYCODE_BACK){screen=HOME;menu=0;save();invalidate();return true;}if(won){next();return true;}
        switch(key){case KeyEvent.KEYCODE_DPAD_LEFT:game.move(who,-1,0);sfx.play(CozySfx.Sound.MOVE);break;case KeyEvent.KEYCODE_DPAD_RIGHT:game.move(who,1,0);sfx.play(CozySfx.Sound.MOVE);break;case KeyEvent.KEYCODE_DPAD_UP:game.move(who,0,-1);sfx.play(CozySfx.Sound.MOVE);break;case KeyEvent.KEYCODE_DPAD_DOWN:game.move(who,0,1);sfx.play(CozySfx.Sound.MOVE);break;case KeyEvent.KEYCODE_BUTTON_A:case KeyEvent.KEYCODE_DPAD_CENTER:case KeyEvent.KEYCODE_ENTER:int x=game.cursorX[who],y=game.cursorY[who];if(gentleCheck&&!game.puzzle.solution[y][x]){game.puzzle.marks[y][x]=2;game.moves[who]++;toast="Not this one — try nearby  ♥";toastAt=System.currentTimeMillis();sfx.play(CozySfx.Sound.ERROR);}else{game.mark(who,(byte)1);game.puzzle.autoCrossCompletedLines(x,y);sfx.play(CozySfx.Sound.FILL);}break;case KeyEvent.KEYCODE_BUTTON_B:case KeyEvent.KEYCODE_BUTTON_X:game.mark(who,(byte)2);sfx.play(CozySfx.Sound.CROSS);break;case KeyEvent.KEYCODE_BUTTON_Y:if(hintsOn&&game.hint(who)){game.puzzle.autoCrossCompletedLines(game.cursorX[who],game.cursorY[who]);toast="A little sparkle showed the way  ✦";toastAt=System.currentTimeMillis();sfx.play(CozySfx.Sound.HINT);}break;default:return super.onKeyDown(key,e);}check();invalidate();return true;}
    @Override public boolean onGenericMotionEvent(MotionEvent e){if((e.getSource()&InputDevice.SOURCE_JOYSTICK)==0||e.getAction()!=MotionEvent.ACTION_MOVE)return super.onGenericMotionEvent(e);int id=e.getDeviceId();if(!players.containsKey(id))players.put(id,players.size()%2);int who=players.get(id);float x=e.getAxisValue(MotionEvent.AXIS_X),y=e.getAxisValue(MotionEvent.AXIS_Y);if(Math.abs(x)>.7f||Math.abs(y)>.7f){long now=System.currentTimeMillis();Long old=lastMove.get(id);if(old==null||now-old>180){lastMove.put(id,now);if(screen==GAME){game.move(who,Math.abs(x)>.7f?(x>0?1:-1):0,Math.abs(y)>.7f?(y>0?1:-1):0);sfx.play(CozySfx.Sound.MOVE);}else if(Math.abs(y)>.7f){menu=Math.floorMod(menu+(y>0?1:-1),5);sfx.play(CozySfx.Sound.MOVE);}invalidate();}}return true;}
    private void check(){if(!won&&game.puzzle.complete()){won=true;sfx.play(CozySfx.Sound.WIN);save();}}
    private void next(){won=false;sfx.play(CozySfx.Sound.SELECT);game.next();save();invalidate();}
    private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align align){p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(android.graphics.Typeface.create("sans",android.graphics.Typeface.BOLD));c.drawText(s,x,y,p);}
    private String joined(int[] clue){StringBuilder b=new StringBuilder();for(int n:clue){if(b.length()>0)b.append(' ');b.append(n);}return b.toString();}
    private void panel(Canvas c,float l,float t,float r,float b,int alpha){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(alpha,43,37,62));rect.set(l,t,r,b);c.drawRoundRect(rect,28,28,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb(130,255,243,220));c.drawRoundRect(rect,28,28,p);}

    @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();rect.set(0,0,w,h);Bitmap scene=screen==GAME&&(game.solved/2)%2==1?garden:background;c.drawBitmap(scene,null,rect,p);p.setColor(Color.argb(screen==GAME?145:55,25,18,38));p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);if(screen==HOME){drawHome(c,w,h);return;}if(screen==SETTINGS){drawSettings(c,w,h);return;}drawGame(c,w,h);}
    private void drawHome(Canvas c,float w,float h){panel(c,w*.28f,h*.06f,w*.72f,h*.94f,224);text(c,"♥",w/2,h*.16f,32,PINK,Paint.Align.CENTER);text(c,"COZYGRAMS",w/2,h*.24f,50,CREAM,Paint.Align.CENTER);text(c,"Puzzles are better together",w/2,h*.30f,19,BLUE,Paint.Align.CENTER);String mode=game.storyMode?"STORY "+(game.storyIndex+1)+" / "+PuzzleLibrary.count():"ENDLESS "+game.size+"×"+game.size;String[] items={"CONTINUE  •  "+mode,"STORY BOOK","ENDLESS SIZE   ‹  "+(game.storyMode?5:game.size)+"×"+(game.storyMode?5:game.size)+"  ›","SOUND, HINTS & HELP","RESTART STORY"};for(int i=0;i<5;i++){float y=h*.40f+i*56;if(i==menu){p.setColor(PINK);p.setStyle(Paint.Style.FILL);rect.set(w*.345f,y-34,w*.655f,y+14);c.drawRoundRect(rect,17,17,p);}text(c,items[i],w/2,y,18,i==menu?BG:CREAM,Paint.Align.CENTER);}text(c,"D-pad / stick to move  •  A to choose",w/2,h*.89f,15,Color.rgb(215,204,220),Paint.Align.CENTER);}
    private void drawSettings(Canvas c,float w,float h){panel(c,w*.27f,h*.08f,w*.73f,h*.92f,235);text(c,"COZY CORNER",w/2,h*.20f,38,CREAM,Paint.Align.CENTER);String[] items={"MUSIC   "+(musicOn?"♥  ON":"OFF"),"SOUND EFFECTS   "+(sfxOn?"♥  ON":"OFF"),"GENTLE MISTAKE CHECK   "+(gentleCheck?"ON":"OFF"),"Y BUTTON HINTS   "+(hintsOn?"ON":"OFF"),"BACK TO MENU"};for(int i=0;i<5;i++){float y=h*.32f+i*59;if(i==menu){p.setColor(PINK);p.setStyle(Paint.Style.FILL);rect.set(w*.335f,y-35,w*.665f,y+15);c.drawRoundRect(rect,17,17,p);}text(c,items[i],w/2,y,17,i==menu?BG:CREAM,Paint.Align.CENTER);}text(c,"A fill  •  B/X cross  •  Y hint  •  ☰ pause",w/2,h*.83f,16,BLUE,Paint.Align.CENTER);text(c,"Each controller gets its own cursor",w/2,h*.88f,14,CREAM,Paint.Align.CENTER);}
    private void drawGame(Canvas c,float w,float h){text(c,"COZYGRAMS",42,56,30,PINK,Paint.Align.LEFT);String progress=game.storyMode?"Story "+(game.storyIndex+1)+" / "+PuzzleLibrary.count():"Endless "+(game.solved+1);text(c,progress+"  •  "+game.size+"×"+game.size,42,92,18,CREAM,Paint.Align.LEFT);float clue=game.size<=10?100:130;float board=Math.min(h-clue-45,w-500);float cell=board/game.size;float left=(w-board+clue)/2,top=(h-board+clue)/2;p.setStyle(Paint.Style.FILL);p.setColor(CREAM);rect.set(left-clue-9,top-clue-9,left+board+9,top+board+9);c.drawRoundRect(rect,18,18,p);
        for(int y=0;y<game.size;y++)text(c,joined(game.puzzle.rowClues(y)),left-12,top+(y+.68f)*cell,Math.min(20,cell*.42f),game.puzzle.rowSolved(y)?PINK:GRID,Paint.Align.RIGHT);for(int x=0;x<game.size;x++){int[] cs=game.puzzle.colClues(x);float fs=Math.min(20,cell*.4f);int color=game.puzzle.colSolved(x)?PINK:GRID;for(int i=0;i<cs.length;i++)text(c,""+cs[i],left+(x+.5f)*cell,top-10-(cs.length-1-i)*fs,fs,color,Paint.Align.CENTER);}
        for(int y=0;y<game.size;y++)for(int x=0;x<game.size;x++){float l=left+x*cell,t=top+y*cell;p.setStyle(Paint.Style.FILL);p.setColor(game.puzzle.marks[y][x]==1?PINK:Color.rgb(255,250,239));c.drawRect(l,t,l+cell,t+cell,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth((x%5==0||y%5==0)?2.5f:1);p.setColor(GRID);c.drawRect(l,t,l+cell,t+cell,p);if(game.puzzle.marks[y][x]==2){p.setStrokeWidth(Math.max(2,cell*.06f));c.drawLine(l+cell*.25f,t+cell*.25f,l+cell*.75f,t+cell*.75f,p);c.drawLine(l+cell*.75f,t+cell*.25f,l+cell*.25f,t+cell*.75f,p);}}
        drawCursor(c,left,top,cell,0,PINK);drawCursor(c,left,top,cell,1,BLUE);float side=left+board+30;text(c,"ROSE  ♥  "+game.moves[0],side,top+25,18,PINK,Paint.Align.LEFT);text(c,"SKY   ♥  "+game.moves[1],side,top+55,18,BLUE,Paint.Align.LEFT);text(c,"A  Fill",side,top+108,16,CREAM,Paint.Align.LEFT);text(c,"B / X  Cross",side,top+136,16,CREAM,Paint.Align.LEFT);text(c,"Y  Hint",side,top+164,16,hintsOn?BLUE:GRID,Paint.Align.LEFT);text(c,"☰  Pause",side,top+192,16,CREAM,Paint.Align.LEFT);if(System.currentTimeMillis()-toastAt<4000||toastAt==0)text(c,toast,w/2,h-24,16,CREAM,Paint.Align.CENTER);
        if(won){panel(c,w*.18f,h*.10f,w*.82f,h*.90f,242);drawReveal(c,w/2,h*.27f,Math.min(220,h*.29f));text(c,"♥  "+game.puzzle.name+"  ♥",w/2,h*.52f,36,PINK,Paint.Align.CENTER);text(c,messages[game.solved%messages.length],w/2,h*.62f,23,CREAM,Paint.Align.CENTER);text(c,"Solved together in "+(game.moves[0]+game.moves[1])+" cozy moves",w/2,h*.70f,17,Color.rgb(215,204,220),Paint.Align.CENTER);text(c,"Press any button for another cozy puzzle",w/2,h*.80f,18,BLUE,Paint.Align.CENTER);drawHearts(c,w,h);postInvalidateOnAnimation();}}
    private void drawReveal(Canvas c,float cx,float cy,float size){float cell=size/game.size,l=cx-size/2,t=cy-size/2;p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(255,248,232));rect.set(l-9,t-9,l+size+9,t+size+9);c.drawRoundRect(rect,15,15,p);for(int y=0;y<game.size;y++)for(int x=0;x<game.size;x++)if(game.puzzle.marks[y][x]==1){float hue=(x+y)/(float)(game.size*2);p.setColor(blend(PINK,BLUE,hue*.55f));c.drawRoundRect(l+x*cell+1,t+y*cell+1,l+(x+1)*cell-1,t+(y+1)*cell-1,Math.max(1,cell*.12f),Math.max(1,cell*.12f),p);}}
    private int blend(int a,int b,float f){return Color.rgb((int)(Color.red(a)*(1-f)+Color.red(b)*f),(int)(Color.green(a)*(1-f)+Color.green(b)*f),(int)(Color.blue(a)*(1-f)+Color.blue(b)*f));}
    private void drawHearts(Canvas c,float w,float h){long tick=System.currentTimeMillis()/35;for(int i=0;i<14;i++){float phase=(tick+i*17)%130/130f;float x=w*(.22f+.56f*((i*47)%101)/100f);float y=h*(.88f-.74f*phase);float sway=(float)Math.sin(phase*9+i)*18;text(c,"♥",x+sway,y,14+(i%4)*3,Color.argb((int)(220*(1-phase)),255,120+(i%2)*55,170+(i%3)*28),Paint.Align.CENTER);}}
    private void drawCursor(Canvas c,float l,float t,float cell,int who,int color){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(3,cell*.10f));p.setColor(color);float in=who==0?3:8;rect.set(l+game.cursorX[who]*cell+in,t+game.cursorY[who]*cell+in,l+(game.cursorX[who]+1)*cell-in,t+(game.cursorY[who]+1)*cell-in);c.drawRoundRect(rect,5,5,p);}
}
