package com.cozygrams.tv;

import android.content.Context;
import android.content.SharedPreferences;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.RectF;
import android.view.InputDevice;
import android.view.KeyEvent;
import android.view.MotionEvent;
import android.view.View;
import java.util.HashMap;
import java.util.Map;

public final class CozyGameView extends View {
    private static final int HOME=0,GAME=1,SETTINGS=2;
    private static final int BG=Color.rgb(43,37,62),CREAM=Color.rgb(255,243,220),PINK=Color.rgb(255,120,154),BLUE=Color.rgb(103,197,220),GRID=Color.rgb(104,91,126);
    private final Paint p=new Paint(3);private final RectF rect=new RectF();private final GameState game;private final CozyMusic music=new CozyMusic();private final Bitmap background,garden;
    private final Map<Integer,Integer> players=new HashMap<>();private final Map<Integer,Long> lastMove=new HashMap<>();
    private int screen=HOME,menu;private boolean won,musicOn;private String toast="Press a button on each controller to join";private long toastAt;
    private final String[] messages={"You make a lovely team!","Piece by piece, you can do anything.","Home is wherever we're together.","Two hearts, one cozy puzzle.","Small steps make beautiful pictures.","The best view is the one we share."};

    public CozyGameView(Context c){super(c);setFocusable(true);setFocusableInTouchMode(true);requestFocus();background=BitmapFactory.decodeResource(getResources(),R.drawable.cozy_room);garden=BitmapFactory.decodeResource(getResources(),R.drawable.moon_garden);SharedPreferences s=c.getSharedPreferences("save",0);long seed=s.getLong("seed",System.currentTimeMillis());int size=s.getInt("size",5);musicOn=s.getBoolean("music",true);game=new GameState(seed,size);game.solved=s.getInt("solved",0);String marks=s.getString("marks","");if(marks.length()==size*size)for(int i=0;i<marks.length();i++)game.puzzle.marks[i/size][i%size]=(byte)(marks.charAt(i)-'0');}
    public void resume(){music.setEnabled(musicOn);}
    public void pause(){music.stop();save();}
    private void save(){StringBuilder b=new StringBuilder(game.size*game.size);for(byte[] row:game.puzzle.marks)for(byte mark:row)b.append((char)('0'+mark));getContext().getSharedPreferences("save",0).edit().putLong("seed",game.seed).putInt("size",game.size).putInt("solved",game.solved).putBoolean("music",musicOn).putString("marks",b.toString()).apply();}
    private int player(KeyEvent e){int id=e.getDeviceId();if(!players.containsKey(id)){players.put(id,players.size()%2);toast="Player "+(players.get(id)+1)+" joined  ♥";toastAt=System.currentTimeMillis();}return players.get(id);}
    private boolean confirm(int key){return key==KeyEvent.KEYCODE_BUTTON_A||key==KeyEvent.KEYCODE_DPAD_CENTER||key==KeyEvent.KEYCODE_ENTER;}

    @Override public boolean onKeyDown(int key,KeyEvent e){if(e.getRepeatCount()>0)return true;int who=player(e);
        if(screen==HOME){if(key==KeyEvent.KEYCODE_DPAD_UP)menu=Math.floorMod(menu-1,4);else if(key==KeyEvent.KEYCODE_DPAD_DOWN)menu=(menu+1)%4;else if(menu==1&&(key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_DPAD_RIGHT||confirm(key))){int step=key==KeyEvent.KEYCODE_DPAD_LEFT?-5:5;game.size+=step;if(game.size>20)game.size=5;if(game.size<5)game.size=20;game.seed=System.currentTimeMillis();game.puzzle=PuzzleGenerator.generate(game.seed,game.size);save();}else if(confirm(key)){if(menu==0)screen=GAME;else if(menu==2){screen=SETTINGS;menu=0;}else if(menu==3){game.seed=System.currentTimeMillis();game.size=5;game.solved=0;game.puzzle=PuzzleGenerator.generate(game.seed,5);save();screen=GAME;}}invalidate();return true;}
        if(screen==SETTINGS){if(key==KeyEvent.KEYCODE_DPAD_UP||key==KeyEvent.KEYCODE_DPAD_DOWN)menu=1-menu;else if(confirm(key)&&menu==0){musicOn=!musicOn;music.setEnabled(musicOn);save();}else if((confirm(key)&&menu==1)||key==KeyEvent.KEYCODE_BACK||key==KeyEvent.KEYCODE_BUTTON_B){screen=HOME;menu=0;}invalidate();return true;}
        if(key==KeyEvent.KEYCODE_BUTTON_START){screen=SETTINGS;menu=0;invalidate();return true;}if(key==KeyEvent.KEYCODE_BACK){screen=HOME;menu=0;save();invalidate();return true;}if(won){next();return true;}
        switch(key){case KeyEvent.KEYCODE_DPAD_LEFT:game.move(who,-1,0);break;case KeyEvent.KEYCODE_DPAD_RIGHT:game.move(who,1,0);break;case KeyEvent.KEYCODE_DPAD_UP:game.move(who,0,-1);break;case KeyEvent.KEYCODE_DPAD_DOWN:game.move(who,0,1);break;case KeyEvent.KEYCODE_BUTTON_A:case KeyEvent.KEYCODE_DPAD_CENTER:case KeyEvent.KEYCODE_ENTER:game.mark(who,(byte)1);break;case KeyEvent.KEYCODE_BUTTON_B:case KeyEvent.KEYCODE_BUTTON_X:game.mark(who,(byte)2);break;default:return super.onKeyDown(key,e);}check();invalidate();return true;}
    @Override public boolean onGenericMotionEvent(MotionEvent e){if((e.getSource()&InputDevice.SOURCE_JOYSTICK)==0||e.getAction()!=MotionEvent.ACTION_MOVE)return super.onGenericMotionEvent(e);int id=e.getDeviceId();if(!players.containsKey(id))players.put(id,players.size()%2);int who=players.get(id);float x=e.getAxisValue(MotionEvent.AXIS_X),y=e.getAxisValue(MotionEvent.AXIS_Y);if(Math.abs(x)>.7f||Math.abs(y)>.7f){long now=System.currentTimeMillis();Long old=lastMove.get(id);if(old==null||now-old>180){lastMove.put(id,now);if(screen==GAME)game.move(who,Math.abs(x)>.7f?(x>0?1:-1):0,Math.abs(y)>.7f?(y>0?1:-1):0);else if(Math.abs(y)>.7f){int count=screen==HOME?4:2;menu=Math.floorMod(menu+(y>0?1:-1),count);}invalidate();}}return true;}
    private void check(){if(game.puzzle.complete()){won=true;save();}}
    private void next(){won=false;game.next();save();invalidate();}
    private void text(Canvas c,String s,float x,float y,float size,int color,Paint.Align align){p.setStyle(Paint.Style.FILL);p.setColor(color);p.setTextSize(size);p.setTextAlign(align);p.setTypeface(android.graphics.Typeface.create("sans",android.graphics.Typeface.BOLD));c.drawText(s,x,y,p);}
    private String joined(int[] clue){StringBuilder b=new StringBuilder();for(int n:clue){if(b.length()>0)b.append(' ');b.append(n);}return b.toString();}
    private void panel(Canvas c,float l,float t,float r,float b,int alpha){p.setStyle(Paint.Style.FILL);p.setColor(Color.argb(alpha,43,37,62));rect.set(l,t,r,b);c.drawRoundRect(rect,28,28,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(2);p.setColor(Color.argb(130,255,243,220));c.drawRoundRect(rect,28,28,p);}

    @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),h=getHeight();rect.set(0,0,w,h);Bitmap scene=screen==GAME&&(game.solved/2)%2==1?garden:background;c.drawBitmap(scene,null,rect,p);p.setColor(Color.argb(screen==GAME?145:55,25,18,38));p.setStyle(Paint.Style.FILL);c.drawRect(0,0,w,h,p);if(screen==HOME){drawHome(c,w,h);return;}if(screen==SETTINGS){drawSettings(c,w,h);return;}drawGame(c,w,h);}
    private void drawHome(Canvas c,float w,float h){panel(c,w*.29f,h*.08f,w*.71f,h*.92f,220);text(c,"♥",w/2,h*.20f,38,PINK,Paint.Align.CENTER);text(c,"COZYGRAMS",w/2,h*.29f,54,CREAM,Paint.Align.CENTER);text(c,"Puzzles are better together",w/2,h*.36f,20,BLUE,Paint.Align.CENTER);String[] items={"CONTINUE","BOARD SIZE   ‹  "+game.size+"×"+game.size+"  ›","MUSIC & HELP","NEW JOURNEY"};for(int i=0;i<4;i++){float y=h*.48f+i*61;if(i==menu){p.setColor(PINK);p.setStyle(Paint.Style.FILL);rect.set(w*.355f,y-36,w*.645f,y+15);c.drawRoundRect(rect,18,18,p);}text(c,items[i],w/2,y,19,i==menu?BG:CREAM,Paint.Align.CENTER);}text(c,"Use D-pad and A to choose",w/2,h*.87f,15,Color.rgb(215,204,220),Paint.Align.CENTER);}
    private void drawSettings(Canvas c,float w,float h){panel(c,w*.28f,h*.15f,w*.72f,h*.85f,232);text(c,"COZY CORNER",w/2,h*.29f,40,CREAM,Paint.Align.CENTER);String[] items={"MUSIC   "+(musicOn?"♥  ON":"OFF"),"BACK TO MENU"};for(int i=0;i<2;i++){float y=h*.47f+i*76;if(i==menu){p.setColor(PINK);p.setStyle(Paint.Style.FILL);rect.set(w*.36f,y-40,w*.64f,y+17);c.drawRoundRect(rect,18,18,p);}text(c,items[i],w/2,y,20,i==menu?BG:CREAM,Paint.Align.CENTER);}text(c,"A  fill     B / X  cross     ☰  pause",w/2,h*.70f,18,BLUE,Paint.Align.CENTER);text(c,"Each controller gets its own cursor",w/2,h*.77f,16,CREAM,Paint.Align.CENTER);}
    private void drawGame(Canvas c,float w,float h){text(c,"COZYGRAMS",42,56,30,PINK,Paint.Align.LEFT);text(c,"Puzzle "+(game.solved+1)+"  •  "+game.size+"×"+game.size,42,92,18,CREAM,Paint.Align.LEFT);float clue=game.size<=10?100:130;float board=Math.min(h-clue-45,w-500);float cell=board/game.size;float left=(w-board+clue)/2,top=(h-board+clue)/2;p.setStyle(Paint.Style.FILL);p.setColor(CREAM);rect.set(left-clue-9,top-clue-9,left+board+9,top+board+9);c.drawRoundRect(rect,18,18,p);
        for(int y=0;y<game.size;y++)text(c,joined(game.puzzle.rowClues(y)),left-12,top+(y+.68f)*cell,Math.min(20,cell*.42f),GRID,Paint.Align.RIGHT);for(int x=0;x<game.size;x++){int[] cs=game.puzzle.colClues(x);float fs=Math.min(20,cell*.4f);for(int i=0;i<cs.length;i++)text(c,""+cs[i],left+(x+.5f)*cell,top-10-(cs.length-1-i)*fs,fs,GRID,Paint.Align.CENTER);}
        for(int y=0;y<game.size;y++)for(int x=0;x<game.size;x++){float l=left+x*cell,t=top+y*cell;p.setStyle(Paint.Style.FILL);p.setColor(game.puzzle.marks[y][x]==1?PINK:Color.rgb(255,250,239));c.drawRect(l,t,l+cell,t+cell,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth((x%5==0||y%5==0)?2.5f:1);p.setColor(GRID);c.drawRect(l,t,l+cell,t+cell,p);if(game.puzzle.marks[y][x]==2){p.setStrokeWidth(Math.max(2,cell*.06f));c.drawLine(l+cell*.25f,t+cell*.25f,l+cell*.75f,t+cell*.75f,p);c.drawLine(l+cell*.75f,t+cell*.25f,l+cell*.25f,t+cell*.75f,p);}}
        drawCursor(c,left,top,cell,0,PINK);drawCursor(c,left,top,cell,1,BLUE);float side=left+board+30;text(c,"P1  ♥",side,top+25,20,PINK,Paint.Align.LEFT);text(c,"P2  ♥",side,top+57,20,BLUE,Paint.Align.LEFT);text(c,"A  Fill",side,top+112,17,CREAM,Paint.Align.LEFT);text(c,"B / X  Cross",side,top+141,17,CREAM,Paint.Align.LEFT);text(c,"☰  Pause",side,top+170,17,CREAM,Paint.Align.LEFT);if(System.currentTimeMillis()-toastAt<4000||toastAt==0)text(c,toast,w/2,h-24,16,CREAM,Paint.Align.CENTER);
        if(won){panel(c,w*.18f,h*.10f,w*.82f,h*.90f,242);drawReveal(c,w/2,h*.29f,Math.min(230,h*.31f));text(c,"♥  "+game.puzzle.name+"  ♥",w/2,h*.55f,38,PINK,Paint.Align.CENTER);text(c,messages[game.solved%messages.length],w/2,h*.66f,24,CREAM,Paint.Align.CENTER);text(c,"Press any button for another cozy puzzle",w/2,h*.79f,18,BLUE,Paint.Align.CENTER);drawHearts(c,w,h);postInvalidateOnAnimation();}}
    private void drawReveal(Canvas c,float cx,float cy,float size){float cell=size/game.size,l=cx-size/2,t=cy-size/2;p.setStyle(Paint.Style.FILL);p.setColor(Color.rgb(255,248,232));rect.set(l-9,t-9,l+size+9,t+size+9);c.drawRoundRect(rect,15,15,p);for(int y=0;y<game.size;y++)for(int x=0;x<game.size;x++)if(game.puzzle.marks[y][x]==1){float hue=(x+y)/(float)(game.size*2);p.setColor(blend(PINK,BLUE,hue*.55f));c.drawRoundRect(l+x*cell+1,t+y*cell+1,l+(x+1)*cell-1,t+(y+1)*cell-1,Math.max(1,cell*.12f),Math.max(1,cell*.12f),p);}}
    private int blend(int a,int b,float f){return Color.rgb((int)(Color.red(a)*(1-f)+Color.red(b)*f),(int)(Color.green(a)*(1-f)+Color.green(b)*f),(int)(Color.blue(a)*(1-f)+Color.blue(b)*f));}
    private void drawHearts(Canvas c,float w,float h){long tick=System.currentTimeMillis()/35;for(int i=0;i<14;i++){float phase=(tick+i*17)%130/130f;float x=w*(.22f+.56f*((i*47)%101)/100f);float y=h*(.88f-.74f*phase);float sway=(float)Math.sin(phase*9+i)*18;text(c,"♥",x+sway,y,14+(i%4)*3,Color.argb((int)(220*(1-phase)),255,120+(i%2)*55,170+(i%3)*28),Paint.Align.CENTER);}}
    private void drawCursor(Canvas c,float l,float t,float cell,int who,int color){p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(Math.max(3,cell*.10f));p.setColor(color);float in=who==0?3:8;rect.set(l+game.cursorX[who]*cell+in,t+game.cursorY[who]*cell+in,l+(game.cursorX[who]+1)*cell-in,t+(game.cursorY[who]+1)*cell-in);c.drawRoundRect(rect,5,5,p);}
}
